### ISSUE TITLE
python run_3dSwap.py 

### ISSUE THREAD

**Issue by qym77** [lyx0208/3dSwap#11]
F:\anaconda3\envs\3dSwap\lib\site-packages\torch\utils\cpp_extension.py:304: UserWarning: Error checking compiler version for cl: [WinError 2] 系统找不到指定的文件。
  warnings.warn(f'Error checking compiler version for {compiler}: {error}')
信息: 用提供的模式无法找到文件。

**Comment by qym77** [comment]
UserWarning: Error checking compiler version for cl: [WinError 2] 系统找不到指定的文件。
  warnings.warn(f'Error checking compiler version for {compiler}: {error}')
信息: 用提供的模式无法找到文件。
Traceback (most recent call last):
  File "run_3dSwap.py", line 2, in <module>
    from models.faceswap_coach import FaceSwapCoach
  File "C:\Users\q1m\Desktop\3dSwap\models\faceswap_coach.py", line 1, in <module>
    from models.encoders.psp_encoders import GradualStyleEncoder
  File "C:\Users\q1m\Desktop\3dSwap\models\encoders\psp_encoders.py", line 8, in <module>
    from models.stylegan2.model import EqualLinear
  File "C:\Users\q1m\Desktop\3dSwap\models\stylegan2\model.py", line 7, in <module>
    from models.stylegan2.op import FusedLeakyReLU, fused_leaky_relu, upfirdn2d
  File "C:\Users\q1m\Desktop\3dSwap\models\stylegan2\op\__init__.py", line 1, in <module>
    from .fused_act import FusedLeakyReLU, fused_leaky_relu
  File "C:\Users\q1m\Desktop\3dSwap\models\stylegan2\op\fused_act.py", line 9, in <module>
    fused = load(
  File "F:\anaconda3\envs\3dSwap\lib\site-packages\torch\utils\cpp_extension.py", line 1079, in load
    return _jit_compile(
  File "F:\anaconda3\envs\3dSwap\lib\site-packages\torch\utils\cpp_extension.py", line 1292, in _jit_compile
    _write_ninja_file_and_build_library(
  File "F:\anaconda3\envs\3dSwap\lib\site-packages\torch\utils\cpp_extension.py", line 1391, in _write_ninja_file_and_build_library
    _write_ninja_file_to_build_library(
  File "F:\anaconda3\envs\3dSwap\lib\site-packages\torch\utils\cpp_extension.py", line 1823, in _write_ninja_file_to_build_library
    _write_ninja_file(
  File "F:\anaconda3\envs\3dSwap\lib\site-packages\torch\utils\cpp_extension.py", line 1947, in _write_ninja_file
    cl_paths = subprocess.check_output(['where',
  File "F:\anaconda3\envs\3dSwap\lib\subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "F:\anaconda3\envs\3dSwap\lib\subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['where', 'cl']' returned non-zero exit status 1.

sorry，new to code，after some difficult install all the requirements，then i run python run_3dSwap.py have some problem，how can i fix it？or how can i understand errors maybe？because i no nothing about this error i guess

**Comment by takuphilchan** [comment]
@qym77 The problem is that it can't locate the compiler in your system. Try to check if it's installed if not install Visual Studio C++ compiler and add it to system paths then try again.
